// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/logger.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LOG int32

const (
	LOG_TRANSACTION LOG = 0
	LOG_PAYMENT     LOG = 0
	LOG_NEWUSER     LOG = 1
	LOG_MAINTENANCE LOG = 2
)

// Enum value maps for LOG.
var (
	LOG_name = map[int32]string{
		0: "TRANSACTION",
		// Duplicate value: 0: "PAYMENT",
		1: "NEWUSER",
		2: "MAINTENANCE",
	}
	LOG_value = map[string]int32{
		"TRANSACTION": 0,
		"PAYMENT":     0,
		"NEWUSER":     1,
		"MAINTENANCE": 2,
	}
)

func (x LOG) Enum() *LOG {
	p := new(LOG)
	*p = x
	return p
}

func (x LOG) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LOG) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logger_proto_enumTypes[0].Descriptor()
}

func (LOG) Type() protoreflect.EnumType {
	return &file_proto_logger_proto_enumTypes[0]
}

func (x LOG) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LOG.Descriptor instead.
func (LOG) EnumDescriptor() ([]byte, []int) {
	return file_proto_logger_proto_rawDescGZIP(), []int{0}
}

type LogInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message     string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	InitiatedBy string `protobuf:"bytes,2,opt,name=initiatedBy,proto3" json:"initiatedBy,omitempty"`
	Date        string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	PersonId    string `protobuf:"bytes,4,opt,name=personId,proto3" json:"personId,omitempty"`
	Other       string `protobuf:"bytes,5,opt,name=other,proto3" json:"other,omitempty"`
	Type        LOG    `protobuf:"varint,6,opt,name=type,proto3,enum=LOG" json:"type,omitempty"`
}

func (x *LogInput) Reset() {
	*x = LogInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInput) ProtoMessage() {}

func (x *LogInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInput.ProtoReflect.Descriptor instead.
func (*LogInput) Descriptor() ([]byte, []int) {
	return file_proto_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogInput) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *LogInput) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LogInput) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *LogInput) GetOther() string {
	if x != nil {
		return x.Other
	}
	return ""
}

func (x *LogInput) GetType() LOG {
	if x != nil {
		return x.Type
	}
	return LOG_TRANSACTION
}

type LogOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stored bool `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
}

func (x *LogOutput) Reset() {
	*x = LogOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutput) ProtoMessage() {}

func (x *LogOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutput.ProtoReflect.Descriptor instead.
func (*LogOutput) Descriptor() ([]byte, []int) {
	return file_proto_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogOutput) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

var File_proto_logger_proto protoreflect.FileDescriptor

var file_proto_logger_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x04, 0x2e, 0x4c, 0x4f, 0x47, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x4a, 0x04, 0x08,
	0x07, 0x10, 0x0b, 0x22, 0x23, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x2a, 0x47, 0x0a, 0x03, 0x4c, 0x4f, 0x47, 0x12,
	0x0f, 0x0a, 0x0b, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x4e, 0x45, 0x57, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x41,
	0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x02, 0x1a, 0x04, 0x10, 0x01, 0x18,
	0x00, 0x32, 0x32, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x21, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x09,
	0x2e, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0a, 0x2e, 0x4c, 0x6f, 0x67, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_logger_proto_rawDescOnce sync.Once
	file_proto_logger_proto_rawDescData = file_proto_logger_proto_rawDesc
)

func file_proto_logger_proto_rawDescGZIP() []byte {
	file_proto_logger_proto_rawDescOnce.Do(func() {
		file_proto_logger_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_logger_proto_rawDescData)
	})
	return file_proto_logger_proto_rawDescData
}

var file_proto_logger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logger_proto_goTypes = []interface{}{
	(LOG)(0),          // 0: LOG
	(*LogInput)(nil),  // 1: LogInput
	(*LogOutput)(nil), // 2: LogOutput
}
var file_proto_logger_proto_depIdxs = []int32{
	0, // 0: LogInput.type:type_name -> LOG
	1, // 1: LoggerService.StoreLog:input_type -> LogInput
	2, // 2: LoggerService.StoreLog:output_type -> LogOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_logger_proto_init() }
func file_proto_logger_proto_init() {
	if File_proto_logger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_logger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_logger_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logger_proto_goTypes,
		DependencyIndexes: file_proto_logger_proto_depIdxs,
		EnumInfos:         file_proto_logger_proto_enumTypes,
		MessageInfos:      file_proto_logger_proto_msgTypes,
	}.Build()
	File_proto_logger_proto = out.File
	file_proto_logger_proto_rawDesc = nil
	file_proto_logger_proto_goTypes = nil
	file_proto_logger_proto_depIdxs = nil
}
