// Letter of credit Router 

// GET 
// @params 
// 
// <hefaId>:<date>
//
// POST
// @params 
// 
// <email:string> <hefaId:string> <amountReq:int> <particular:string> 
// <status:string> <amountGiven:int> <validatedBy:string> <date:string>
//
// DELETE
// @params 
// 
// !xx
// 
// PATCH
// @params 
//
// !xx
// 
// @id 
// <hefaId>:<date>

// Roles : 
// (i) create pdf
// (ii) send pdf
// (iii) Synchronizes with data router
// (iv) delete pdf

// STATUS CODES
// 200 - Success Operation
// 201 - Success Creation
// 404 - Not found
// 500 - Server Error
// 403 - Forbidden Request

// Requirements
const express = require("express");
const cors = require("cors");
const path = require('path');
const bodyparser = require("body-parser");
const htmlpdf = require("html-pdf");
const util = require("./../../../controller/utils");

// LetterOfCredit Router
const hefaReqRouter = express.Router();

// Template
const pdfTemplate = require("../../../views/template/hefaReq");

// Stores pdf with <hefaid>:<date> as unique identifier

const gen_file_name = "hefa_request";
const FILE_NAME = "hefaReq.js";
const ROUTER_NAME = "hefaReqRouter";

// Middleware
hefaReqRouter.use(cors());
hefaReqRouter.use(bodyparser.urlencoded({ extended: true }));
hefaReqRouter.use(bodyparser.json());

// POST - to make server to genarate pdf
// GET - after making post request - again we need to ask the server to give the pdf generated by it

// Creates pdf
// notifies frontend that it has created the pdf
// Content : req.body

// Client will not about pdf storing in webs server 
hefaReqRouter.post("/:hefaId/:date", (req, res) => {
	const debugText = util.RDebugText(FILE_NAME, "POST", ROUTER_NAME);
    console.log(debugText);
	
	const hefaId = req.params.hefaId;
	const date = req.params.date;

	htmlpdf
		.create(pdfTemplate(req.body), {})
		.toFile(`${gen_file_name}_${date}_${hefaId}.pdf`, (err) => {
			if (err) {
				console.log(util.ErrorStream(FILE_NAME,"CREATING",`${gen_file_name}-pdf not created`,err));
				res.send({err:err});
				Promise.reject();
			}
			console.log(util.DebugStream(FILE_NAME,"SUCCESS",`${gen_file_name}-pdf created`));
			res.send(Promise.resolve());
		});
});

hefaReqRouter.get("/:hefaId/:date", (req, res) => {
	const debugText = util.RDebugText(FILE_NAME, "GET", ROUTER_NAME);
    console.log(debugText);

	const hefaId = req.params.hefaId;
	const date = req.params.date;

	const curr_path = path.normalize(`${__dirname}\\..\\..\\..\\`);
	res.sendFile(`${curr_path}/${gen_file_name}_${date}_${hefaId}.pdf`);
	console.log(util.DebugStream(FILE_NAME,"SUCCESS",`${gen_file_name}-pdf sent`));
});

module.exports = hefaReqRouter;